---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: job-scheduler
  namespace: transcode
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: job-scheduler-role
  namespace: transcode
rules:
  - apiGroups: ["batch", "extensions"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "watch", "list"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "watch", "list"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["get", "create"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: job-scheduler-rolebinding
  namespace: transcode
subjects:
  - kind: ServiceAccount
    name: job-scheduler
roleRef:
  kind: Role
  name: job-scheduler-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-scheduler
  namespace: transcode
  labels:
    app: job-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: job-scheduler
  template:
    metadata:
      labels:
        app: job-scheduler
    spec:
      serviceAccountName: job-scheduler
      containers:
      - name: "scheduler"
        image: <OCIR repo path>/scheduler:latest
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: transcoder-config
        command: ["python3", "/app/consumer.py"]
      imagePullSecrets:
        - name: ocirsecret
      nodeSelector:
        name: nodepool2
